### ISSUE TITLE
About Running Code Issues

### ISSUE THREAD

**Issue by hsb1995** [ZO-Bench/ZO-LLM#1]
My current situation is as follows: After downloading the weight file and configuring the environment, I cannot run it according to your prompt. There have also been many situations, could you please explain them.
![image](https://github.com/ZO-Bench/ZO-LLM/assets/149936473/748bf025-877f-4c60-9829-8aaee312c26f)
I really didn't understand what you meant in the example you gave. In the discussion, I see that I am the only one inquiring about this question. Could you please answer it.
![image](https://github.com/ZO-Bench/ZO-LLM/assets/149936473/ee6c19f3-6169-4641-918d-fa8bd8ea5633)

**Comment by jyhong836** [comment]
You need to register at wandb.ai first.
Try `wandb login`.
