### ISSUE TITLE
Optimal Hyperparameter for each Gridseach

### ISSUE THREAD

**Issue by mshaocong** [ZO-Bench/ZO-LLM#7]
Thank you very much for releasing such high-quality code.  I was wondering if there is a resource available where we can find the final performance of each hyper-parameter or the optimal hyper-parameter for each sweep configuration. From my understanding, Table 2 in your paper reports the best result from the grid search. Is that correct? It would be much more convenience for us if we could directly access the optimal hyper-parameters without having to run the grid search again. 

BTW, I have a small comment regarding the sweep configuration file [https://github.com/ZO-Bench/ZO-LLM/blob/main/zo-bench/sweeps/SST2_opt-1.3b/sgd/sgd_cls_ft.yml](https://github.com/ZO-Bench/ZO-LLM/blob/main/zo-bench/sweeps/SST2_opt-1.3b/sgd/sgd_cls_ft.yml). It appears that the model name is listed as `opt-13b` , but it should be `opt-1.3b`.

**Comment by pingzhili** [comment]
Thanks for bringing this up, we are collecting the optimal hyper-parameters for each sweep and will release them ASAP.

**Comment by mshaocong** [comment]
> Thanks for bringing this up, we are collecting the optimal hyper-parameters for each sweep and will release them ASAP.

Thank you for the update. Looking forward to the release!
