### ISSUE TITLE
Why is q>1 not memory efficient in the zo_step_v2 function?

### ISSUE THREAD

**Issue by Johnny1145** [ZO-Bench/ZO-LLM#8]

**Comment by jyhong836** [comment]
In this case, we can not use the trick of caching random seed and therefore the memory efficiency is low.

**Comment by Johnny1145** [comment]
> In this case, we can not use the trick of caching random seed and therefore the memory efficiency is low.

Thank you.
What is the purpose of the zo_step_v2 function? I noticed it uses random_seed_list, which seems similar to the memory efficiency implementation with n > 1 sampling in the MEZO paper.

**Comment by jyhong836** [comment]
That one is not efficient, though. You may try.
